theme: jekyll-theme-dinky
url: https://dmort27.github.io/subwordmodeling/
title: "Subword Modeling"
show_downloads: false
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
exclude: [ util, analysis, vendor ]
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-theme-dinky
defaults:
  -
    scope:
      path: "_lectures"
    values:
      layout: "lecture"
  -
    scope:
      path: "_assignments"
    values:
      layout: "assignment"
  -
    scope:
        path: ""
    values:
        layout: "default"
collections:
    lectures:
        output: true
    assignments:
        output: true
